# Generated by Django 4.0 on 2023-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('lat_long', models.TextField()),
                ('f_details', models.TextField()),
            ],
        ),
    ]
