# Generated by Django 4.0 on 2023-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
