# Generated by Django 4.0 on 2023-06-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_food', '0002_remove_hotel_id_alter_hotel_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_id',
            new_name='id',
        ),
    ]
